version: 1
formatters:
  fileFormatter:
    format: "%(asctime)s %(funcName)s %(levelname)s %(message)s"
  consoleFormatter:
    format: "%(levelname)s %(message)s"
handlers:
  fileHandler:
    class: logging.handlers.RotatingFileHandler
    formatter: fileFormatter
    level: DEBUG
    filename: gamma_bch_usd.log
    maxBytes: 10485760
    backupCount: 100
  consoleHandler:
    class: logging.StreamHandler
    formatter: consoleFormatter
    level: INFO
    stream: ext://sys.stdout
loggers:
  root:
    level: INFO
    handlers: [consoleHandler]
  gamma:
    level: DEBUG
    handlers: [fileHandler, consoleHandler]
